--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DanteDEVS/ThrowableSword
build-by-default: true
branches:
- main
projects:
  ThrowableSword:
    path: ""
    icon: "sword.png" 
    libs:
      - src: DanteDEVS/DanteDevs
        version: ^1.0.0
...
